name: phonlab_desktop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.4.*
  - pip
  - scipy==1.15
  - pyqt6==6.11
  - pyqtgraph==0.14
  - librosa==0.11
  - numba
  - pip:
    - phonlab==0.0.58
    - sounddevice==0.5.5
    - soundfile==0.13.1
    - pyqt6-sip==13.12
