on:
  push:
    branches: [ "main" ]

jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12.13'
          spec: 'src/phonlab_desktop.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Phonlab'
          options: --onefile, --name "My App", --windowed,
          
